### ISSUE TITLE
Annotate plots with genome features

### ISSUE THREAD

**Issue by flashton2003** [chienchi/amplicon_coverage_plot#3]
Hello,

I really like amplicov, so thank you!

I think it would be really cool to be able to pass another bed file with some features to highlight on the plot, e.g. spike protein for SARS-CoV-2, or other features of interest. And then these could be displayed on the plot so that it would be easy to see which parts of the genome are suffering amplicon dropouts for example.

Anyway, just an idea.

Thanks again,

Phil

**Comment by chienchi** [comment]
I think it is good idea with some other annotation can be view on the plot. Since it is not plot by genome coordinates, I think other annotations will be like on the hover text information. I will think about more on this.  Thank you.

**Comment by flashton2003** [comment]
Brilliant, thank you!

**Comment by chienchi** [comment]
commit 94308f9b,   add --gff flag for annotation data.
