### ISSUE TITLE
amplicov requires tabs at the end of the line

### ISSUE THREAD

**Issue by flashton2003** [chienchi/amplicon_coverage_plot#4]
Hello,

I started using a new bed file for a different primer scheme and I was getting the below error:

Traceback (most recent call last):
  File "/home/phil/miniconda3/envs/artic/bin/amplicov", line 448, in <module>
    run(argvs)
  File "/home/phil/miniconda3/envs/artic/bin/amplicov", line 420, in run
    amplicon_dict = covert_bed_to_amplicon_dict(argvs.bed,cov_array,argvs.refID)
  File "/home/phil/miniconda3/envs/artic/bin/amplicov", line 86, in covert_bed_to_amplicon_dict
    primers_pos.extend(range(int(rstart),int(rend)+1))
ValueError: invalid literal for int() with base 10: 'nCoV-2019_1'

'nCoV-2019_1'  was the last value on the first line of the bedfile.

By comparing with a working BED file, I noticed that the working bedfile had tabs at the end of each line (i.e. it was 'nCoV-2019_1\t\n').

When I added tabs to the end of the lines, it worked for my different primer scheme.

Is this intended behaviour?

Thanks,

Phil

**Comment by chienchi** [comment]
Hi Phil,

The last column of support bed6 file is strand information. Usually it noted as '+' or '-'.  I have updated the README to specific to bed6 format and links to the description from bedtools. In addition, I tried to add a simple bed6 file check and report which line has the issue. baf2dab318b151eee3856fd9004656cf24e10edf 

Thanks,
Chienchi

**Comment by flashton2003** [comment]
Ah, I see. Good to know. Thanks!
