### ISSUE TITLE
Consider primer trimming

### ISSUE THREAD

**Issue by nbx0** [chienchi/amplicon_coverage_plot#5]
Many thanks for this useful tool. One issue we've had is in calling some amplicons as 0 coverage when they are 100% overlapped by adjacent amplicon+primers. I think I found a solution for us but would appreciate your insight into unintentional effects. 

![image](https://user-images.githubusercontent.com/39743838/145404348-8da493df-ad1b-4ece-ba68-79ca5a9a27a2.png)
In this example, amplicon 77 is reported as 0 unique coverage, however our pipeline removes primers and thus the positions where the center pair of primers (78R and 79L) sits is unique to amplicon 77. 

I made the following hacks and amplicov seems to be reporting what I expect now:
```python
101         for i in range(int(fend),int(rstart)+1):
...
105         unique_region_set = set(np.where(cov_zero_array == 1)[0]) #- set(primers_pos)
...
139         for i in range(int(fend),int(rstart)+1):
...
143         unique_region_set = set(np.where(cov_zero_array == 1)[0]) #- set(primers_pos)
```

What unintended effects might this have? I believe this could be a useful setting for further development.

Thanks!
Ben

**Comment by chienchi** [comment]
Yes. I didn't think about the data has been trimmed by primer. I think your implementation make senes to me. I will incorporate that as an option for user to turn on the overlapped primer region count.
